name: deploy-client

on:
  push:
    branches:
      - master
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: cd client && docker build -t managervcf/client .
      - name: Login into docker hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image to docker hub
        run: docker push managervcf/client
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Configure kubectl to use Digital Ocean context tick-it
        run: doctl kubernetes cluster kubeconfig save tick-it
      - name: Restart deployment
        run: kubectl rollout restart deployment client-depl
